### ISSUE TITLE
打包apk后 安装到模拟器提示Sequence contains no matching element

### ISSUE THREAD

**Issue by lingfan** [xhaoh94/UxGame#1]
InvalidOperationException: Sequence contains no matching element
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <00000000000000000000000000000000>:0)
Ux.HotFixMgr.Load () (at <00000000000000000000000000000000>:0)
Ux.HotFixMgr.Init () (at <00000000000000000000000000000000>:0)
Ux.PatchDone.OnEnter () (at <00000000000000000000000000000000>:0)
Ux.StateMachine.Enter (System.String entryNode) (at <00000000000000000000000000000000>:0)
Ux.Downloader._Download (System.Action`1[T] end) (at <00000000000000000000000000000000>:0)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].TrySetResult (TResult result) (at <00000000000000000000000000000000>:0)
Ux.Downloader._Download () (at <00000000000000000000000000000000>:0)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].TrySetResult (TResult result) (at <00000000000000000000000000000000>:0)
YooAsset.AsyncOperationBase.SetFinish () (at <00000000000000000000000000000000>:0)
YooAsset.OperationSystem.Update () (at <00000000000000000000000000000000>:0)
YooAsset.YooAssets.Update () (at <00000000000000000000000000000000>:0)
Ux.StateMachine:Enter(String)
Ux.<_Download>d__33:MoveNext()
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(TResult)
Ux.<_Download>d__35:MoveNext()
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(TResult)
YooAsset.AsyncOperationBase:SetFinish()
YooAsset.OperationSystem:Update()
YooAsset.YooAssets:Update()

![image](https://github.com/xhaoh94/UxGame/assets/455872/b76c0e35-6c2e-45be-a8c3-b119c88ad699)

**Comment by lingfan** [comment]
tuanjie 引擎不支持

**Comment by lingfan** [comment]
团结 和 2022.3.19f1 都不行

**Comment by xhaoh94** [comment]
> 团结 和 2022.3.19f1 都不行

你这是AOT dll 跟第一次打包的版本对不上的问题。你是使用的项目里带的打包程序吗？

**Comment by xhaoh94** [comment]
你可以先前往hybridclr 看下常见错误。我回家过年了，没带电脑在身边。短时间内无法看

**Comment by lingfan** [comment]
对的 第一次打包 我想第一次打个本地包 不需要热更 不过每次打出来都提示要热更 我研究研究 谢谢

**Comment by lingfan** [comment]
HOTFIX_CODE 没有这个定义 导致 走错了业务
